### ISSUE TITLE
The redux state is not submitted

### ISSUE THREAD

**Issue by NameFILIP** [ngokevin/redux-raven-middleware#11]
I use 

```
applyMiddleware(
  ravenMiddleware('https://***@app.getsentry.com/***')),
  thunk,
  logger
);
```

I can see the breadcrumbs:

```
redux   MY_ACTION   00:45:53
```

but there is no `state` in the "Additional Data".

If I insert a fake error here https://github.com/ngokevin/redux-raven-middleware/blob/master/index.es6#L27 the state will be submitted, but otherwise, looks like the error doesn't come out of `next(action)`

**Comment by akhayoon** [comment]
So apparently it's only supposed to give you the Redux state for issues in your Reducers and Actions and not your components. Which is not enough for me.

Your setup didn't work for me either and I ended up having to add the `state` using the Raven callback in another thread suggested here.

In my configureStore.js `createStore()` function

```       
 applyMiddleware(middleware, createDebounce(), thunkMiddleware, 
            // We init Raven here, so we can use RavenMiddleware to get:
            // 1) Redux action breadcrubms (useful for debugging)
            // 2) current state of the store (not working here, so we use the dataCallback to insert out own)
        	RavenMiddleware(
        		'***sentry dsn***,
                {
                    release: '2.0',
                    dataCallback: (data) => 
                    {
                        callbackRavenMiddleware(data);
                    }
                }
        	)
        )
```

dataCallback is called just before an error is sent to Sentry.


In my app.js I have this function exported and then imported by name in configureStore.js
I got this code from another issue posted here. With the difference of not declaring the store inside the function.

The `store.getState()` should reference the store declared in your app.js file already that is being passed into your top-level Root.jsx component

```
export function callbackRavenMiddleware(data)
{
    if (!(data.extra && data.extra.state)) 
    {
        try 
        {
            data.extra.state = store.getState();
        } 
        catch (expt) 
        {
            console.log(expt);
        }
    }
    return data;
}
```

The reason I have it in app.js is because store.getState() needs to be the Current State and you can't get the Current  State in configureStore.js because that's where the Store is created. 

So far this is working for me. So in the end raven-redux-middlware just gives me the action breadcrumbs which are still pretty useful. It's not working for me to show the current state of the store.

**Comment by captbaritone** [comment]
I've implemented an alternative library which, after each action, attaches the current state to Raven as context. This means that all exceptions will include your current state as context, not just exceptions encountered within your reducer. You can find it here: https://github.com/captbaritone/raven-for-redux

If this is an approach that redux-raven-middleware would like to adopt, I'd be happy to open a pull request.

**Comment by tomaswitek** [comment]
Thx @captbaritone, exactly what I was looking for.
I stared your repo 😏
