### ISSUE TITLE
Enable setting of user context

### ISSUE THREAD

**Issue by ccastarivale** [ngokevin/redux-raven-middleware#28]
Raven allows setting a specific user context for better tracking. As far as I can tell, there is no way to set it when using this module. https://docs.sentry.io/clients/ruby/context/#user-context

**Comment by captbaritone** [comment]
[raven-for-redux](https://github.com/captbaritone/raven-for-redux) take the slightly different approach of expecting you to setup Raven yourself. This means you have direct access to the `Raven` object and can easily call `setUserContext` yourself.

(Just in case there is any confusion, I see you have linked to the Ruby docs. Here is the correct Raven-js docs link: https://docs.sentry.io/clients/javascript/#adding-context

I've added a test to raven-for-redux to ensure that setting user context works: https://github.com/captbaritone/raven-for-redux/commit/61ee3b04472a75e0fb168c7f76b0a06d47fa172d

**Comment by ccastarivale** [comment]
Thanks for pointing me to the right docs. To have access to Raven, sounds like I must switch to using `raven-for-redux` directly rather than relying on `redux-raven-middleware`, correct?

**Comment by captbaritone** [comment]
Correct. The API is very similar, expect that import/configure Raven yourself, rather than passing Raven's config to the middleware creator. Take a look at the example in `raven-for-redux`'s readme, and feel free to reach out if you have any questions. I'll be idling in this Gitter room if you need help: https://gitter.im/raven-for-redux/Lobby
